# Generated by Django 3.2.9 on 2022-09-13 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyskill',
            old_name='name',
            new_name='keyskill_name',
        ),
        migrations.RenameField(
            model_name='keysubskill',
            old_name='name',
            new_name='keysubskill_name',
        ),
    ]
