# Generated by Django 3.2.9 on 2022-09-13 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0002_auto_20220913_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyskill',
            old_name='keyskill_name',
            new_name='keyskill_text',
        ),
        migrations.RenameField(
            model_name='keysubskill',
            old_name='keysubskill_name',
            new_name='keysubskill_text',
        ),
    ]
