# Generated by Django 3.2.9 on 2022-09-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0004_auto_20220913_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyskill',
            name='iconName',
        ),
        migrations.AddField(
            model_name='keyskill',
            name='icon',
            field=models.FileField(default='tech-icons/1.png', upload_to='tech-icons\\1.png'),
            preserve_default=False,
        ),
    ]
