# Generated by Django 3.2.9 on 2022-09-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0006_alter_keyskill_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keysubskill',
            name='iconName',
        ),
        migrations.AddField(
            model_name='keyskill',
            name='activeColor',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keysubskill',
            name='icon',
            field=models.ImageField(default='subtech-icons/java.png', upload_to='subtech-icons'),
            preserve_default=False,
        ),
    ]
