# Generated by Django 3.2.9 on 2022-09-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0007_auto_20220914_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keysubskill',
            name='icon',
            field=models.ImageField(upload_to='tech-icons'),
        ),
    ]
