# Generated by Django 3.2.9 on 2022-09-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0008_alter_keysubskill_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multilinguality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('ru', models.CharField(max_length=1000)),
                ('en', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='keyskill',
            name='icon',
            field=models.ImageField(default=None, null=True, upload_to='tech-icons'),
        ),
        migrations.AlterField(
            model_name='keysubskill',
            name='icon',
            field=models.ImageField(default=None, null=True, upload_to='tech-icons'),
        ),
    ]
