# Generated by Django 3.2.9 on 2022-09-26 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0009_auto_20220920_1611'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Multilinguality',
        ),
    ]
