# Generated by Django 3.2.9 on 2022-09-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesiredPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('banner', models.ImageField(default=None, null=True, upload_to='position-baners')),
                ('status', models.CharField(max_length=500)),
                ('status_en', models.CharField(max_length=500, null=True)),
                ('status_ru', models.CharField(max_length=500, null=True)),
                ('salary_rub', models.DecimalField(decimal_places=2, max_digits=9)),
                ('salary_usd', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
