# Generated by Django 3.2.9 on 2022-09-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_desiredposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desiredposition',
            name='salary_usd',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
