# Generated by Django 3.2.9 on 2022-09-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_desiredposition_salary_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desiredposition',
            name='status',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
