# Generated by Django 3.2.9 on 2022-09-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_desiredposition_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desiredposition',
            name='banner',
            field=models.ImageField(default=None, upload_to='position-baners'),
        ),
        migrations.AlterField(
            model_name='desiredposition',
            name='salary_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='desiredposition',
            name='status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='desiredposition',
            name='status_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='desiredposition',
            name='status_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
