# Generated by Django 3.2.9 on 2022-09-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220929_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(verbose_name='actual')),
                ('rateRub', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
