# Generated by Django 3.2.9 on 2022-09-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_exrates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exrates',
            name='rateRub',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
