# Generated by Django 3.2.9 on 2022-10-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_exrates_raterub'),
    ]

    operations = [
        migrations.AddField(
            model_name='desiredposition',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
