# Generated by Django 3.2.9 on 2022-10-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_desiredposition_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desiredposition',
            name='status',
        ),
        migrations.RemoveField(
            model_name='desiredposition',
            name='status_en',
        ),
        migrations.RemoveField(
            model_name='desiredposition',
            name='status_ru',
        ),
        migrations.AddField(
            model_name='desiredposition',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desiredposition',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desiredposition',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
